config/routes.rb
Rails.application.routes.draw do
  root to: 'site#index'

  resources :donors do
    member do
      put 'cancel'
      put 'uncancel'
    end
    collection do
      get 'exists'
      put 'verify'
      get 'thanks'
      get 'fetch_state_by_zip'
      get 'map'
      post 'payment_receipt'
    end
  end

  resources :nonprofits do
    get 'autotweet', on: :member
    get 'upcoming_report', on: :collection
  end

  resources :subscribers, param: :guid do
    member do
      get 'unsubscribe',                action: 'unsubscribe',  as: 'unsubscribe'
      put 'unsubscribe'
      put 'resubscribe'
      get 'donations',                  action: 'donations'
      get 'email_login/:auth_token',    action: 'email_login',  as: 'email_login'
      get 'logout',                     action: 'logout'
    end
    collection do
      get 'thanks'
    end
  end

  devise_for :users, :skip => [:registrations]
  devise_scope :user do
    get "login"      => "devise/sessions#new"
    get 'users/edit' => 'devise/registrations#edit',   as: 'edit_user_registration'
    put 'users'      => 'devise/registrations#update', as: 'user_registration'
  end

  resources :users

  # These were added by hugh
  get  'volunteer',        to: 'site#volunteer'
  get  'account',          to: 'site#account',       as: :account
  get  'donate',           to: 'donors#info',        as: :donate
  get  'donate/:id',       to: 'donors#new',         as: :new_donation

  #TODO: Scrub below routes
  get  'about',            to: 'site#about'
  get  'calendar',         to: 'site#calendar'
  get  'faq',              to: 'site#faq'
  get  'subscribe',        to: 'subscribers#new',    as: :subscribe
  post 'donate',           to: 'donors#create'
  get  'legal',            to: 'site#legal'
  get  'contact',          to: 'site#contact'
  post 'send_feedback',    to: 'site#send_feedback'
  get  'wall_calendar',    to: 'site#wall_calendar'
  get  'autotweet',        to: 'site#autotweet'
  # Share to app (or) mobile browser javascript
  get 'share',             to: 'site#share',         as: :share

  # Admin
  get '/admin/mailers'         => "admin/mailers#index"
  get '/admin/mailers/*path'   => "admin/mailers#preview"

  namespace :admin do
    get 'delayed_jobs', to: 'base#delayed_jobs'

    resources :categories
    resources :nonprofits do
      collection do
        get :lookup_ein
      end
    end
    resources :activations
    resources :donors, except: [:new, :create]
    resources :donations
    resources :subscribers
    resources :stats
    resources :payouts, only: [:index, :create]
  end

  get '/health' => 'application#health'
end

app/models/donor.rb
class Donor < ActiveRecord::Base

  belongs_to :user
  NEW_USER_FIELDS = [
    :password,
    :password_confirmation
  ]
  attr_accessor *NEW_USER_FIELDS

  belongs_to :subscriber, touch: true
  has_many   :donations

  has_many   :cards, class_name: 'DonorCard'
  has_one    :card, -> { DonorCard.active }, class_name: 'DonorCard', inverse_of: :donor

  has_many   :nonprofits_donated_to,
             -> { order(featured_on: :desc) },
             through: :donations,
             source: :donated_nonprofits

  accepts_nested_attributes_for :card
  accepts_nested_attributes_for :subscriber

  validates :user, uniqueness: true, presence: true
  validates :subscriber, uniqueness: true, presence: true
  validates :guid, uniqueness: true, if: :guid_changed?

  scope :active,    -> { where(finished_on: nil, failed_at: nil) }
  scope :inactive,  -> { where("finished_on <= ? OR failed_at IS NOT NULL", Date.today) }
  scope :cancelled, -> { where.not(cancelled_at: nil) }
  scope :failed,    -> { where.not(failed_at: nil) }
  scope :subscribed,        -> { joins(:subscriber).merge(Subscriber.active) }
  scope :unsubscribed,      -> { joins(:subscriber).merge(Subscriber.inactive) }
  scope :with_public_names, -> { where.not(public_name: ["", nil]) }

  STRIPE_FIELDS = [
    :stripe_token
  ]

  attr_accessor *STRIPE_FIELDS

  audited

  def stripe?; stripe_customer_id.present?; end

  # # Get all the donors that have a donation to this nonprofit
  scope :for_nonprofit, ->(n) {
    joins(donations: [:nonprofits]).where("nonprofits.id = ?", n.id)
  }

  def to_param
    subscriber.try(:guid)
  end

  def has_duplicates?
    nonprofit_ids = donations.flat_map { |d| d.donation_nonprofits.pluck(:nonprofit_id) }
    nonprofit_ids.size != nonprofit_ids.uniq.size
  end

  def self.check_for_duplicate_donations
    donor_ids = Donor.all.select(&:has_duplicates?).map(&:id)
    AdminMailer.duplicate_donations(donor_ids).deliver if donor_ids.present?
  end

  def self.find_by_param(val)
    where(id: val).first || find(val)
  end

  # Regularly check/nullify donors who have left their active period (>30 days
  # after their last charge, aka after their last daily $1 donation).
  def self.finish_cancelled_donors
    Donor.active.cancelled.each do |donor|
      last_donation = donor.last_executed_donation
      if last_donation.blank? || Time.now > (last_donation.scheduled_at + 30.days)
        donor.card.try(:deactivate!)
        donor.update_attribute(:finished_on, Time.zone.now.to_date)
      end
    end
  end

  def active_subscriber?
    subscriber.try(:active?)
  end

  def cancelled?
    cancelled_at.present?
  end

  def active?
    !inactive?
  end

  def failed?
    failed_at.present?
  end

  def inactive?
    failed? || finished_on.present?
  end

  def last_executed_donation
    donations.executed.order("executed_at DESC").first
  end

  def cancel!(notify_donor: true)
    return if cancelled?

    transaction do
      donations.pending.update_all(cancelled_at: Time.now)
      self.cancelled_at = Time.now
      self.uncancelled_at = nil
      save!
      # SendCancelledJob.new(self.id).save if notify_donor @TODO: Dmitri uncomment when jobs are back in the mix for emails
    end
  end

  def uncancel!
    return unless cancelled?

    transaction do
      last_donation = donations.executed.last
      next_donation_at = [
        (30.days.since(last_donation.scheduled_at) if last_donation), # for cancelled/active donors
        finished_on,  # for cancelled/inactive donors (this *should* actually be the same as the above, if finished_on is present)
        Time.now      # bare minimum
      ].compact.max

      # schedule at 12am
      donations.build(scheduled_at: next_donation_at.beginning_of_day)
      self.uncancelled_at = Time.now
      self.finished_on  = nil
      self.cancelled_at = nil
      save!
      SendUncancelledJob.new(self.id).save
    end
  end

  private

  after_create :schedule_first_donation
  def schedule_first_donation
    donations.create(scheduled_at: Time.now)
  end

  before_validation :preprocess, on: :create
  def preprocess
    self.started_on                 = Time.zone.now.to_date
    self.guid                       = guid.presence || SecureRandom.hex(16)
    if s = Subscriber.without_donor.where(email: card.email).first
      self.subscriber = s
    end

    build_subscriber if subscriber.blank?

    subscriber.name                 = card.name       if subscriber.name.blank? # populate the subscriber's name (means they existed already)
    subscriber.email                = card.email      if subscriber.email.blank?
    subscriber.ip_address           = card.ip_address if subscriber.ip_address.blank?
  end
end

app/controllers/admin/donors_controller.rb
class Admin::DonorsController < Admin::BaseController
  before_filter :find_donor, only: [:show]

  def index
    @q = Donor.search(params[:q])
    @donors = @q.result(distinct: true).includes(:card, :subscriber)
  end

  def find_donor
    @donor = Donor.find_by_param(params[:id])
  end

  def show
  end

end

app/controllers/donors_controller.rb
require 'mandrill'

class DonorsController < ApplicationController
  protect_from_forgery :except => :payment_receipt

  before_filter :authenticate_user!, only: :index
  before_filter :admin_required, only: :index
  before_filter :require_donor, only: [:uncancel, :edit, :update]
  before_filter :initialize_donor, only: [:new, :create]

  respond_to :html, except: [:exists, :fetch_state_by_zip, :map]
  respond_to :json, only: [:exists, :fetch_state_by_zip, :map]

  def index
    @donors = Donor.active.order("created_at ASC")
    @subscriber = Subscriber.new
  end

  def new
    redirect_to account_path and return if current_user.present?
    @require_stripe_js = true
    @hide_footer = true
    @public_theme = "green"

    if params[:email].present?
      @subscriber = Subscriber.where(email: params[:email].to_s).first_or_initialize
      @donor.subscriber = @subscriber
      @donor.build_card(email: @subscriber.email)
    end

    @nonprofit = Nonprofit.find_by_param(params[:id])
    page_meta_tags
    respond_with(@donor, layout: "public")
  end

  def info
    @require_stripe_js = true
    @public_theme      = "green"
    @categories        = Category.all

    # @TODO: Unsure if this is needed
    if params[:email].present?
      @subscriber = Subscriber.where(email: params[:email].to_s).first_or_initialize
      @donor.subscriber = @subscriber
      @donor.build_card(email: @subscriber.email)
    end

    @nonprofits = Nonprofit.all

    respond_with(@donor, layout: "public")
  end

  def create
    @require_stripe_js = true
    @hide_header = true
    @hide_footer = true

    @donor.attributes        = donor_params
    @donor.card.ip_address   = request.ip
    @donor.card.stripe_token = params[:stripeToken] if params["stripeToken"].present?

    Donor.transaction do
      @new_user = User.create!({
        email: @donor.card.email,
        name: @donor.card.name,
        password: donor_params[:password],
      })

      # only sign in the user if the non-profit is on the index page
      if @donor.card.nonprofit.is_public
        sign_in @new_user
      end

      @donor.user = @new_user
      @donor.save!
      session[:thanks] = @donor.subscriber.name
      session[:nonprofit_id] = @donor.card.nonprofit.id
      session[:donor_name] = @donor.subscriber.name
      session[:donor_card_amount] = @donor.card.amount
      session[:nonprofit_category] = @donor.card.nonprofit.category.name
      redirect_to thanks_donors_url
    end
    rescue ActiveRecord::RecordInvalid, ActiveRecord::RecordNotSaved => e
    flash[:notice] = e.message
    redirect_to new_donation_url(donor_card_params[:card_attributes][:nonprofit_id])
  end

  # "Change Billing Details"
  def edit
    @require_stripe_js = true
    @new_card = current_donor.cards.new
  end

  # Stripe webhook for when an invoice is successfully paid for
  def payment_receipt
    mandrill = Mandrill::API.new Rails.application.secrets.mandrill_api_key

    event_json = JSON.parse(request.body.read) # event data from Stripe

    if event_json["type"] != "invoice.payment_succeeded"
       render json: {}, status: 400
    else
      donor = Donor.find_by(stripe_customer_id: event_json["data"]["object"]["customer"])
      donor = Donor.find_by(stripe_customer_id: "cus_AT3dv800viOsas") unless donor # @TODO: remove once fully test -- used for integration environment tests temporarily
      DonorMailer.stripe_payment_receipt(donor).deliver_now if donor && event_json["data"]["object"]["amount_due"].to_i != 0
      render json: {}, status: 200
    end
  end

  # TODO cleanup
  def update
    @require_stripe_js = true
    @new_card            = DonorCard.new(donor_card_params[:card_attributes])
    @new_card.ip_address = request.ip
    @new_card.is_active  = false
    @new_card.donor      = current_donor # TODO inverse_of?
    @new_card.stripe_token = params[:stripeToken]
    @new_card.stripe_email = params[:stripeEmail]
    @new_card.save!

    was_failed = current_donor.failed?

    current_donor.reload
    current_donor.cards.active.where.not(id: @new_card.id).each(&:deactivate!)
    @new_card.activate!

    # If they're fixing their card, try the failed donation again.
    if donation = current_donor.donations.failed.first
      donation.fix!
    end

    if was_failed
      flash[:notice] = "Thanks! We'll try it again now, and let you know by email."
    else
      flash[:notice] = "Thanks! We'll use this card from here on out."
    end
    redirect_to root_url
  rescue ActiveRecord::RecordInvalid => e
    render :edit
  end

  def cancel
    # @TODO: DMITRI eventually have this not actually destroy the record (to allow uncancelling)
    # but also send the cancellation email
    @donor_card = DonorCard.find_by(email: current_user.email)
    redirect_to account_path and return if @donor_card.nil?
    @donor = @donor_card.donor
    customer = Stripe::Customer.retrieve(@donor.stripe_customer_id)
    customer.delete # deletes all subscriptions
    @donor.subscriber.destroy
    @donor.destroy
    @donor_card.destroy
    current_user.destroy
    flash[:notice] = "Sorry to see you go!"
    redirect_to root_url
  end

  def uncancel
    @creds = params[:donor_verification]

    # TODO test the @auth_method thing -- this is so users don't have to 2x auth
    #  when going to cancel via website (instead of email)
    if auth_method == :card || current_donor.card.valid_credentials?(@creds[:last_4], @creds[:exp_month], @creds[:exp_year])
      current_donor.uncancel!
      render json: {success: "Thanks, you've signed up to start donating again!"}
    else
      render json: {error: "Sorry, those were not the correct credentials!"}
    end
  end

  # TODO throttle this?
  def exists
    @donor = Subscriber.where(email: params[:email].to_s).first.try(:donor)

    if @donor
      if @donor.active?
        if @donor.cancelled?
          msg = "You've recently canceled. To start donating again, or otherwise manage your account,"
        else
          msg = "You're already a donor. To manage your account"
        end
      else
        msg = "You've recently canceled. To start donating again, or otherwise manage your account,"
      end

      json = { success: true, message: msg }
    else
      json = { success: false }
    end

    respond_to do |format|
      format.json do
        render json: json
      end
    end
  end

  # Verify the donor's info, and pass them on to status page (?)
  def verify
    if verify_donor
      json = { success: true, location: subscriber_url(current_subscriber) }
    else
      json = { success: false, message: "We couldn't verify this account. Please check your info." }
    end

    respond_to do |format|
      format.json do
        render json: json
      end
    end
  end

  def thanks
    @hide_header = true
    @hide_footer = true
    @public_theme = 'green'
    @name = session['thanks']
    @nonprofit = Nonprofit.find(session['nonprofit_id'])
    redirect_to(root_url) and return unless @name = session.delete(:thanks)
    render :thanks, layout: 'public'
  end

  def fetch_state_by_zip
    @json =
      if params[:zip] && params[:zip] =~ /\A\d\d\d\d\d\z/
        city, state = params[:zip].to_region.split(",")
        {city: city.strip, state: state.strip}
      else
        {}
      end
    respond_with(@json)
  end

  def map
    @donors = Donor.active
    @json = []
    @donors.each { |d| @json.push(:latitude => d.subscriber.latitude, :longitude => d.subscriber.longitude, :city => d.subscriber.city) }
    respond_with(@json)
  end

  protected
  def page_meta_tags
    @meta_tags['og:image']        = @nonprofit.photo.url
    @meta_tags['og:title']        = "Donate now: #{@nonprofit.name}"
    @meta_tags['twitter:image']   = "#{@nonprofit.photo.url.gsub(/https/, 'http')}"
    @meta_tags['twitter:title']   = "Donate now: #{@nonprofit.name}"
  end

  private
  def donor_params
    params.require(:donor).permit(
      :add_fee, :password, :public_name, {card_attributes: [:name, :email, :amount, :address_zip, :nonprofit_id ]}
    )
  end

  def donor_card_params
    params.require(:donor).permit(
      card_attributes: [:name, :email, :address_zip, :nonprofit_id ]
    )
  end
end

app/views/donors/_authenticate_form.html.erb
<div id="authenticate-overlay" class="modal-overlay">
  <div class="modal-bg modal-overlay-dark js-modal-overlay-close"></div>
  <div class="modal-content mobile-table full-height">
    <div class="mobile-table-cell">
      <div class="interior js-interior dropshadow relative centered-container margin-auto p4">
        <a href="#" class="js-modal-overlay-close modal-overlay-close"><%= image_tag "clear.svg", width: 20, height: 20 %></a>
        <%= render partial: "donors/verify_form" %>
      </div>
    </div>
  </div>
</div>

app/views/donors/_card_fields.html.erb
<% f = form_builder # the donate form builder object %>
<% card = defined?(card) && card.present? ? card : (f.object.card || DonorCard.new) %>

<%= f.fields_for(:card, card) do |c| %>

  <div class="field mb1">
      <% unless Rails.env.production? -%>
        <span id="donate_test_data_button" style="text-decoration: underline; cursor: pointer;" class="right small">Use Test Data</span>
      <% end %>
      <%= c.label :email, "Your Email #{error_tooltip_for(c.object, :email)}".html_safe %>
      <%= c.text_field :email, autocompletetype: "email", class: "full-width", tabindex: 1 %>
  </div>

  <div class="field mb1">
    <%= c.label :amount, "Amount #{error_tooltip_for(c.object, :amount)}".html_safe %>
    <%= c.text_field :amount, class: "full-width", tabindex: 2 %>
  </div>

  <div class="field mb1">
    <%= c.label :name, "Full name #{error_tooltip_for(c.object, :name)}".html_safe %>
    <%= c.text_field :name, autocompletetype: "given-name", class: "full-width", tabindex: 2 %>
  </div>

  <div class="field mb1">
    <div class="clearfix">
      <%= c.label :card_number, "Card number #{error_tooltip_for(c.object, :card_number)}".html_safe, class: "left" %>
      <div class="right">
        <%= image_tag "checkout/icon-cc-visa.png", width: "35" %>
        <%= image_tag "checkout/icon-cc-amex.png", width: "35" %>
        <%= image_tag "checkout/icon-cc-mastercard.png", width: "35" %>
      </div>
    </div>
    <%= c.text_field :card_number, autocomplete: "off", class: "full-width", tabindex: 3 %>
  </div>


  <div class="field clearfix bottom-padding-fix">
    <div class="left">
      <%= c.label :exp_month, "Expiration date #{error_tooltip_for(c.object, :exp_month)}".html_safe, class: "clearfix" %>
      <div class="select-container mr1 left">
        <%= c.select :exp_month, (1..12).to_a, {}, autocomplete: "off", tabindex: 4 %>
        <span class="ss-icon ss-dropdown"></span>
      </div>
      <div class="select-container mr2 left">
        <%= c.select :exp_year, (Time.zone.now.year..10.years.from_now.year), {}, autocomplete: "off", tabindex: 5 %>
        <span class="ss-icon ss-dropdown"></span>
      </div>
    </div>
    <div class="clearfix relative bottom-padding-fix pl3 mobile-no-padding">
      <%= c.label(:csc) do %>
        <%= "CVV #{error_tooltip_for(c.object, :csc)}".html_safe %>
      <% end %>
      <%= c.text_field :csc, class: "full-width", autocomplete: "off", size: 4, tabindex: 6 %>
    </div>
  </div>


  <div class="field">
    <%= c.label :address1, "Billing address #{error_tooltip_for(c.object, :address1)}".html_safe %>
    <%= c.text_field :address1, class: "full-width", tabindex: 7 %>
  </div>

  <div class="field">
    <%= c.label :city, "City #{error_tooltip_for(c.object, :city)}".html_safe %>
    <%= c.text_field :city, class: "full-width", tabindex: 8 %>
  </div>

  <div class="field">
    <%= c.label :country, "Country #{error_tooltip_for(c.object, :country)}".html_safe %>
    <div class="select-container full-width">
      <%= c.select :country, options_for_select(CARMEN_COUNTRY_OPTIONS, "US"), {}, tabindex: 9 %>
      <span class="ss-icon ss-dropdown"></span>
    </div>
  </div>

  <div class="clearfix field">
    <div class="right pl1 bottom-padding-fix" style="width: 163px;">
      <%= c.label :zip, "Zip/post code #{error_tooltip_for(c.object, :zip)}".html_safe %>
      <%= c.text_field :zip, class: "full-width", autocompletetype: "postal-code", tabindex: 11 %>
    </div>
    <div class="clearfix bottom-padding-fix">
      <%= c.label :state, "State/region #{error_tooltip_for(c.object, :state)}".html_safe %>
      <%= c.text_field :state, id: "donor_card_attributes_region", class: "full-width", tabindex: 10 %>
      <div class="select-container full-width">
        <%= c.select :state, [["Select", nil]] + UNITED_STATES, {}, tabindex: 10  %>
        <span class="ss-icon ss-dropdown"></span>
      </div>
    </div>
  </div>

<% end -%>

app/views/donors/_form.html.erb
<p id="existing_donor_message" style="display: none;">
  <span class="highlight"></span>&nbsp;<%= link_to "click here", account_url, class: "sofiabold white" -%>
</p>

<!-- Selector -->
<div class='account-first-page-options-container flex flex-wrap justify-center bg-accent-color dgray mb4'>
  <div class='account-first-page-options double-border-button col-5 m1'>
    <p class='sofiabold h6 py4 center' data-amount="0.10">$.10 a day</p>
  </div>
  <div class='account-first-page-options double-border-button col-5 m1'>
    <p class='sofiabold h6 py4 center' data-amount="0.25">$.25 a day</p>
  </div>
  <div class='account-first-page-options double-border-button col-5 m1'>
    <p class='sofiabold h6 py4 center' data-amount="0.50">$0.50 a day</p>
  </div>
  <div class='account-first-page-options double-border-button col-5 m1'>
    <p class='sofiabold h6 py4 center' data-amount="1.00">$1.00 a day</p>
  </div>
</div>


<h6 class='steps dgray sofiasemibold caps' id='step3'>Step 3 of 3</h6>
<p class='sub-heading sofiabold pt1 pb2 dgray no-wrap'>
  Enter your billing info
</p>
<p class='h6 MuseoSans300 pb3 lgray'>
  We will transfer your money each month, every 30 days from sign up.
</p>

<section id="other">
  <%= render "donors/stripe_card_fields", form_builder: form_builder %>
</section>

<section id="form_footer" class="clear">
  <div class="field mb1">
    <%= form_builder.text_field :password, tabindex: 11, placeholder: "Password - Must be at least 8 characters", type: "password", autocomplete: :off, autocorrect: "off", spellcheck: "off", autocapitalize: "off", class: "h5 my1 py1 border bg-notwhite sofiabold velure email-enter full-width" %>
  </div>

  <!--
  <div class="checkbox pt1 pb3 relative">
    <%= form_builder.check_box :add_fee, { tabindex: 12 }, "1", "0" %>
    <%= form_builder.label(:add_fee, class: "clearfix MuseoSans300 inline-block") do %>
      <%= "Give an extra $%0.2f per month to cover credit card fees." % stripe_fee_amount  %>
      <a class="tooltip tooltop-offset tablet-hide" title="<div style='width: 300px'>Stripe charges a processing fee. Adding <%= "$%0.2f" % stripe_fee_amount %> per month to your donation allows a full $30 to go to nonprofits.</div>"><span class="ss-icon ss-help"></span></a>
    <% end %>
    </div>
  -->
  <%= form_builder.submit "Donate!", class: "h6 my1 mb4 py2 sofiabold white bg-algae full-width no-border no-outline", tabindex: 13 %>
</section>

app/views/donors/_index.html.erb
<h3>LATEST DONOR</h3>

<h4><%= @latest_donor %> <img src="/images/hand.png" /><span><strong>No.</strong><%= donor_count %></span></h4>

<p id="more_donors">
  <a href=""><img src="/images/more_donors_link.png" alt="-------->" />View all donors</a>
</p>

app/views/donors/_verify_billing_fields.html.erb
<div class="mb2 clearfix">
  <div class="left mobile-no-float">
    <div class="select-container mb1 inline-block">
      <%= select_tag 'donor_verification[exp_month]', options_for_select((1..12).to_a), tabindex: 2 %>
      <span class="ss-icon ss-dropdown"></span>
    </div>
    <div class="select-container mb1 inline-block">
      <%= select_tag 'donor_verification[exp_year]', options_for_select((Time.zone.now.year..10.years.from_now.year)), tabindex: 3 %>
      <span class="ss-icon ss-dropdown"></span>
    </div>
  </div>
  <div class="clearfix pl2 mobile-no-padding">
    <%= text_field_tag 'donor_verification[last_4]', nil, placeholder: "Last 4 Digits", class: "full-width mb1", :autocomplete => "off", tabindex: 4, maxlength: 4 %>
  </div>
</div>

app/views/donors/_verify_form.html.erb
<% form_id ||= "verify_donor" %>

<%= form_tag verify_donors_url(format: :json), method: :put, remote: true, id: form_id, class: "verify_donor_form" do %>
  <p class="message"></p>

  <p>To manage your account, please enter your email:</p>

  <div class="field">
    <%= text_field_tag 'donor_verification[email]', nil, placeholder: "Email", class: "js-focus-on-open full-width", tabindex: 1 %>
  </div>

  <p class="instructions">Next, please enter the last 4 digits and expiration of the credit card used:</p>

  <%= render "donors/verify_billing_fields" %>

  <%= submit_tag "Manage account", class: "button-solid button-green button-big" , id: "manage-account-button", tabindex: 5 %>
<% end -%>

app/views/donors/new.html.erb
<%
  days_left = (@donor.started_on - Time.zone.now.end_of_month.to_date).to_i.abs
  this_month = Date::MONTHNAMES[Time.zone.now.month]
  next_month = Date::MONTHNAMES[Time.zone.now.next_month.month]
%>

<% @page_title = "Become a donor today" %>
<div id='donors-new'>
  <%= render 'donors/form_container' %>
</div>

app/views/donors/thanks.html.erb
<%= content_for :extra_head do %>
  <meta property="og:description" content="<%= Rails.application.secrets.name %> makes giving back to your community easy! <%=root_url%>" />
<% end %>
<div class='clearfix'>
  <div class='col col-12 py4 border-first-panel relative bc-white bg-dewy min-panel-height viewport-height' style='z-index:1'>
    <div class='clearfix pb4 px2 mx-auto max-width-4'>
      <div class='double-border-box-faq biggest-box index-page-box p1'>
        <h3 class='sofiasemibold dgray mb2'>Thank you!</h3>
        <h2 class='sofiasemibold dgray mb4'>
          You care about
          <span class='accent-color'><%= session[:nonprofit_category] %></span>
          and would like to contribute
          <span class='accent-color'>$<%= "%01.2f" % session[:donor_card_amount] %></span>
          everyday.
        </h2>
        <% if @nonprofit.is_public %>
          <%= link_to "Return home", root_path, {
            class: "p2 mx-auto text-decoration-none sofiabold bg-white h6 algae bc-algae button-border button-radius"
          } %>
          <%= link_to "Go to my account", account_path, {
            class: "p2 mx-auto text-decoration-none sofiabold bg-algae h6 white bg-algae button-border bc-algae button-radius"
          } %>
        <% else %>
          <%= link_to "Go Back", new_donation_path(@nonprofit), {
            class: "p2 mx-auto text-decoration-none sofiabold bg-white h6 algae bc-algae button-border button-radius"
          } %>
        <% end %>
        <%= link_to "Tweet", "https://twitter.com/share?text=#{Rails.application.secrets.name},%20I%20did!%20#{Rails.application.secrets.name}%20makes%20giving%20back%20to%20your%20community%20easy!&url=#{root_url}", {
          class: "p2 mx-auto text-decoration-none sofiabold bg-white h6 button-border bc-velure button-radius velure",
          target: '_blank'
        } %>
        <!-- @TODO uncomment once facebook app is setup -->
        <!-- <%= link_to "Share", "http://www.facebook.com/dialog/feed?display=popup&redirect_uri=#{URI.escape(root_url)}&app_id=#{Rails.application.secrets.facebook_app_id}&link=#{URI.escape(root_url)}", {
          class: "p2 mx-auto text-decoration-none sofiabold bg-velure h6 white button-border bc-velure button-radius",
          target: '_blank'
        } %> -->
      </div>
    </div>
  </div>
</div>