config/routes.rb
Rails.application.routes.draw do
  root to: 'site#index'

  resources :donors do
    member do
      put 'cancel'
      put 'uncancel'
    end
    collection do
      get 'exists'
      put 'verify'
      get 'thanks'
      get 'fetch_state_by_zip'
      get 'map'
      post 'payment_receipt'
    end
  end

  resources :nonprofits do
    get 'autotweet', on: :member
    get 'upcoming_report', on: :collection
  end

  resources :subscribers, param: :guid do
    member do
      get 'unsubscribe',                action: 'unsubscribe',  as: 'unsubscribe'
      put 'unsubscribe'
      put 'resubscribe'
      get 'donations',                  action: 'donations'
      get 'email_login/:auth_token',    action: 'email_login',  as: 'email_login'
      get 'logout',                     action: 'logout'
    end
    collection do
      get 'thanks'
    end
  end

  devise_for :users, :skip => [:registrations]
  devise_scope :user do
    get "login"      => "devise/sessions#new"
    get 'users/edit' => 'devise/registrations#edit',   as: 'edit_user_registration'
    put 'users'      => 'devise/registrations#update', as: 'user_registration'
  end

  resources :users

  # These were added by hugh
  get  'volunteer',        to: 'site#volunteer'
  get  'account',          to: 'site#account',       as: :account
  get  'donate',           to: 'donors#info',        as: :donate
  get  'donate/:id',       to: 'donors#new',         as: :new_donation

  #TODO: Scrub below routes
  get  'about',            to: 'site#about'
  get  'calendar',         to: 'site#calendar'
  get  'faq',              to: 'site#faq'
  get  'subscribe',        to: 'subscribers#new',    as: :subscribe
  post 'donate',           to: 'donors#create'
  get  'legal',            to: 'site#legal'
  get  'contact',          to: 'site#contact'
  post 'send_feedback',    to: 'site#send_feedback'
  get  'wall_calendar',    to: 'site#wall_calendar'
  get  'autotweet',        to: 'site#autotweet'
  # Share to app (or) mobile browser javascript
  get 'share',             to: 'site#share',         as: :share

  # Admin
  get '/admin/mailers'         => "admin/mailers#index"
  get '/admin/mailers/*path'   => "admin/mailers#preview"

  namespace :admin do
    get 'delayed_jobs', to: 'base#delayed_jobs'

    resources :categories
    resources :nonprofits do
      collection do
        get :lookup_ein
      end
    end
    resources :activations
    resources :donors, except: [:new, :create]
    resources :donations
    resources :subscribers
    resources :stats
    resources :payouts, only: [:index, :create]
  end

  get '/health' => 'application#health'
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  layout "public"
  before_filter :authenticate_user!, except: [:index, :volunteer]

  def index
    #TODO: Hugh - Scrub this controller - none of these
    @nonprofits = Nonprofit.is_public
    @subscriber = Subscriber.new
  end

  def login
    @nonprofits = Nonprofit.is_public
    @subscriber = Subscriber.new
  end

  def volunteer
    @categories   = Category.all
    @activations  = Activation.is_public
    @subscriber = Subscriber.new
    @public_theme = "orange"
  end

  def account
    @current_user = current_user
  end

  def donate
  end

  def wall_calendar
  end

  def legal
  end

  def faq
  end

  def contact
  end

  def send_feedback
    params[:email] = params[:email].to_s
    params[:message] = params[:message].to_s

    if params[:email] !~ Devise.email_regexp
      flash[:alert] = "Please enter a valid email address."
      render :contact
    elsif params[:message].blank?
      flash[:alert] = "Please enter a message to send."
      render :contact
    else
      SendFeedbackJob.new(params[:email], params[:message]).save
      flash[:notice] = "Thanks! We'll look at your message in a bit."
      redirect_to root_url
    end
  end


  def share
    @full_url = params[:url]
    if @full_url
      @full_url += "&"
    else
      @full_url = [root_url, '?'].join('') if !@full_url
    end
    params.each do |k,v|
        @full_url += "#{k}=#{v}&" if ["redirect_uri", "href", "app_id", "display"].include?(k)
    end
    render :layout => false
  end
end

app/helpers/site_helper.rb
module SiteHelper
end

app/views/site/account.html.erb
<div id='account' class='clearfix'>

  <div class='col col-12 py4 border-first-panel relative bc-white bg-notwhite flex flex-column min-panel-height' style='z-index:1'>
    <div class='col col-12 py4 flex flex-column'>
      <div class='account-first-page-welcome-text col-8 mx-auto'>
        <p class='welcome h2 sofiabold py3 dgray'>
          Welcome, <%= @current_user.first_name %>.
        </p>
        <p class='h5 MuseoSans300 pb3 lgray'>
          What would you like to do?
        </p>
      </div>
      <div class='account-first-page-options-container flex flex-wrap justify-center bg-accent-color dgray'>
        <!-- <div class='account-first-page-options double-border-button col-4 m1'>
          <p class='sofiabold h6 py5 center dgray'>Change my daily amount</p>
        </div>
        <div class='account-first-page-options double-border-button col-4 m1'>
          <p class='sofiabold h6 py5 center dgray'>Change support cause</p>
        </div> -->
        <div class='account-first-page-options double-border-button col-4 m1'>
          <%= link_to(cancel_donor_path(current_user), method: :put, class: "text-decoration-none") do %>
            <p class='sofiabold h6 py5 center dgray'>Stop donating</p>
          <% end %>
        </div>
        <div class='account-first-page-options double-border-button col-4 m1'>
          <%= link_to(destroy_user_session_path, method: :delete, class: "text-decoration-none") do %>
            <p class='sofiabold h6 py5 center dgray'>Sign out</p>
          <% end %>
        </div>
      </div>
    </div>
  </div>

</div>

app/views/site/calendar.html.erb
<article id="content" class="bg-green">
  <section id="intro" class="hero-calendar" data-0="opacity: 1;" data-400="opacity: 0;">
    <div class="container p2" data-0="top: 0px;" data-400="top: -40px;">
      <div class="row">
        <div class="col-center col-8">
          <div class="pt6 pb6">
            <h2 class="white no-margin">Everyone knows about the Red Cross, but what other nonprofits are doing great work?</h2>
          </div>
        </div>
      </div>
    </div>
  </section>

  <div class="js-calendar-pagination-hide relative">

    <section id="calendar" class="js-add-dropshadow">
      <div class="container pl2 pr2 pt6 pb2">
        <div class="row">
          <div class="col-center col-8">

            <h4 class="bold no-margin pb3">Our calendar</h4>

            <p>We'll always have (at least) the next 60 featured nonprofits on this page. Come back to see the future anytime!</p>
            <p><%= link_to "See our full selection criteria", faq_path(anchor: "calendar") %> or browse our calendar of nonprofits below.</p>

          </div>
        </div>
      </div>
    </section>
  </div>

  <section id="nonprofits" class="bg-green">
    <div class="container pt4 pb2 pl2 pr2 clip mobile-no-padding">
      <% if @future_nonprofits.present? %>
        <% @future_nonprofits[0, 30].in_groups_of(2, false).each_with_index do |nonprofit_row, index| %>
          <div class="row">
            <% nonprofit_row.each do |nonprofit| %>
              <div class="non-profit tablet-col tablet-col-6 mb4">
                <div class="non-profit-card-image bg-grey bg-cover bg-center" style="background-image: url(<%= nonprofit.photo.url(:medium)%>)"></div>
                <div class="bg-white p3">
                  <h3><%= nonprofit.name %></h3>
                  <h5 class="bold mb2">
                    <% if nonprofit.featured_on == Time.zone.now.to_date %>
                      Featured nonprofit for today.
                    <% elsif nonprofit.featured_on < Time.zone.now.to_date %>
                      Featured on <%= nonprofit.featured_on.to_formatted_s(:long_ordinal) %>
                    <% else %>
                      Will be featured on <%= nonprofit.featured_on.to_formatted_s(:long_ordinal) %>
                    <% end %>
                  </h5>
                  <% if nonprofit.description.length >= 250 %>
                    <div class="js-read-more">
                      <div class="js-read-more-hide">
                        <p><%= truncate(nonprofit.description, length: 250, omission: "... ") { link_to "Read more", nonprofit_url(nonprofit), class: "green no-wrap js-read-more-link" } %></p>
                      </div>
                      <div class="js-read-more-show hide">
                        <p><%= nonprofit.description %></p>
                        <p class="small"><%= link_to_nonprofit(nonprofit, target: "_blank") %></p>
                      </div>
                    </div>
                  <% else %>
                    <p><%= nonprofit.description %></p>
                    <p class="small"><%= link_to_nonprofit(nonprofit, target: "_blank") %></p>
                  <% end %>
                </div>
              </div>
            <% end %>
          </div>
        <% end %>

        <div class="pt2 pb4 centered" id="calendar_nav_links"
          data-date="<%= @date %>"
          data-previouspage="<%= (@date - 30.days) if @past_nonprofits.present? %>"
          data-nextpage="<%= @future_nonprofits.last.featured_on if @future_nonprofits.size > 30 %>">
        </div>
        <div class="mobile-show pb2">&nbsp;</div>
      <% end %>
    </div>
  </section>
</article>

app/views/site/contact.html.erb
<article id="content" class="table bg-cover pt8 pb8 mobile-no-padding" style="background-image: url(<%= asset_url("blurred-bg.jpg")%>)">

  <div class="table-cell">
    <div class="col-center col-8 bg-green">
      <div class="p4">
        <h2 class="no-margin mb4">How can we help?</h2>
        <p class="mb4">If you want to cancel, <%= link_to "Manage account", "#authenticate-overlay", class: "js-modal-overlay-open" %><br/>
        Have general questions about <%= Rails.application.secrets.name %>, please read our <%= link_to "FAQ", faq_path %>.<br/>
        Other questions, press inquiries, or feedback? Please get in touch below.</p>
        <%= form_tag send_feedback_url, method: :post do -%>
          <div class="field <%= 'field_with_errors' if params[:email] %>">
            <%= label_tag :email, "Email" %>
            <%= text_field_tag :email, params[:email], size: 50, class: "full-width" %>
          </div>

          <div class="field <%= 'field_with_errors' if params[:message] %>">
            <%= label_tag :message, "Message", value: params[:message] %>
            <%= text_area_tag :message, params[:message], rows: 8, cols: 70, class: "full-width" %>
          </div>

          <p><%= submit_tag "Send", class: "button-solid button-green button-big" %></p>
        <% end -%>
      </div>
    </div>

  </div>

</article>

app/views/site/faq.html.erb
<section id="content" class="bg-green pb6">
  <div class="header-shim"></div>
  <div class="container pl2 pr2">
    <div class="col-center col-8">
      <div class="mb4">
        <h3 class="bold mb2">What is <%= Rails.application.secrets.name %>?</h3>
        <p><%= Rails.application.secrets.name %> is a simple new way for people to discover and support nonprofits that do great work.</p>
        <div class="divider"></div>
      </div>
      <div class="mb4">
        <h3 class="bold mb2">How does <%= Rails.application.secrets.name %> work?</h3>
        <div class="divider"></div>
      </div>
      <div class="mb4">
        <h3 class="bold mb2">Who is <%= Rails.application.secrets.name %> for?</h3>
        <p><%= Rails.application.secrets.name %> is for anyone who wants to be more engaged with nonprofits. Finding great organizations can be difficult, and many of us are busier than ever. We wanted to make it easier for people to both discover and support great nonprofits.</p>
        <p>At its heart, <%= Rails.application.secrets.name %> is about discovery. We hope that our daily emails will be a gateway for people to give directly, volunteer for, or simply learn more about a variety of great organizations and the problems they’re trying to solve. A public more fluent in nonprofits and their work is really exciting.</p>
        <div class="divider"></div>
      </div>
      <div class="mb4">
        <h3 class="bold mb2">If I donate, will my credit card be charged $### a day?</h3>
        <p>Nope. Donors are charged on a monthly cycle: $### every 30 days. It keeps things simple and minimizes credit card fees.</p>
        <div class="divider"></div>
      </div>

      <!-- FOR ANCHOR LINK-->
      <div id="calendar"></div>

      <div class="mb4">
        <h3 class="bold mb2">Can I see the calendar of the nonprofits you’ll be featuring?</h3>
        <p>Yes! <%= link_to "Our calendar", calendar_path(ref: "faq") %> will always show (at least) the next 60 days of nonprofits.</p>
        <div class="divider"></div>
      </div>
      <div class="mb4">
        <h3 class="bold mb2">What is your selection criteria for nonprofits?</h3>
        <p> ... text goes here about selection criteria ... </p>
        <div class="divider"></div>
      </div>
      <div class="mb4">
        <h3 class="bold mb2">Can I opt out of donating to certain nonprofits?</h3>
        <p>No. We’ve chosen to keep things simple to start. And we hope that instead of feeling a need to skip nonprofits that might not excite you, you’ll choose to go the other way: learn more, give more, and engage further with those that really grab you.</p>
        <div class="divider"></div>
      </div>
      <div class="mb4">
        <h3 class="bold mb2">Can I suggest a nonprofit?</h3>
        <p>Yes! We would love to hear from you. <a href="https://..." target="_blank">Drop us a line</a>.</p>
        <div class="divider"></div>
      </div>
      <div class="mb4">
        <h3 class="bold mb2">Are donations tax deductible?</h3>
        <p>All donations on <%= Rails.application.secrets.name %> are 100% US tax deductible. You'll get an email receipt when your credit card is charged.</p>
        <div class="divider"></div>
      </div>
      <div class="mb4">
        <h3 class="bold mb2">How do donations get from <%= Rails.application.secrets.name %> to the nonprofits?</h3>
        <p><%= Rails.application.secrets.name %> distributes funds directly to each of our featured nonprofits within 30 days of feature.</p>
        <div class="divider"></div>
      </div>
      <div class="mb4">
        <h3 class="bold mb2">How do I cancel once I’ve started donating?</h3>
        <p>We make it easy, with links to cancel from every daily email. Once you cancel you won’t be charged again, but your last $30 donation will still be distributed to the 30 nonprofits from the date of last donation.</p>
        <p>Even if you stop being a donor, you can still continue to receive our daily email for free!</p>
        <div class="divider"></div>
      </div>
      <div class="mb4">
        <h3 class="bold mb2">Am I going to get mail or email from nonprofits?</h3>
        <p>No. Your donations are processed anonymously. Your name, address, and email are not shared with nonprofits. You can always sign up for more info on any nonprofit’s website.</p>
        <div class="divider"></div>
      </div>
      <div class="mb4">
        <h3 class="bold mb2">Will you ever repeat the same nonprofits?</h3>
        <p>At some point, we may repeat nonprofits &mdash; particularly, those featured in the early days, when fewer people were signed up. We have many hundreds to feature first, though, and we are always looking for more to consider. Know an organization doing good work? <a href="https://..." target="_blank">Suggest a nonprofit</a>.</p>
        <div class="divider"></div>
      </div>
    </div>
  </div>
</section>

app/views/site/index.html.erb
<div class='clearfix'>

  <div class='col col-12 py4 border-first-panel bc-white bg-svelte min-panel-height'>
    <div class='clearfix py4 px2 flex items-center mx-auto max-width-3'>
      <div class='col col-12 py4 flex flex-column center'>
        <p class='mx-auto h1 my0 sofiabold pb3 dgray'><%= Rails.application.secrets.name %> makes giving back to your community<span class='velure'> easy.</span></p>
        <p class='mx-auto h5 MuseoSans300 px2 pb3 lgray'>Connect with the charities and organizations you want to support - online with your wallet, and on the ground with your time.</p>
        <a href='/account'class="pulsate donate-activation-button text-decoration-none p2 nowrap mx-auto sofiabold bg-velure h6 white">Give Now</a>
      </div>
    </div>
  </div>

  <%= render "layouts/public/partials/image_left", locals: {
    img: "public/Hero-Give.png",
    headline: "Donate a small amount to causes ",
    headline_accent: "every day.",
    copy: "Support and subscribe to the causes you believe in by making a small donation each day.",
    cta: "Donate now!"
  } %>

  <%= render "layouts/public/partials/image_right", locals: {
    img: "public/Volunteer.png",
    headline: "Go make a difference by ",
    headline_accent: "volunteering.",
    copy: "Volunteer with local, credible community organization (currently beta testing in NYC).",
    cta: "Volunteer now!"
  } %>

  <div class='faq-panel col col-12 pt4 pb4 min-panel-height'>
    <div class='clearfix pb4 px2 mx-auto max-width-4'>
      <div class='double-border-box-faq biggest-box index-page-box p1 sofiasemibold'>
        <p class='box-inner-text sofiabold h4 dgray'>A platform for activism</p>
        <p class='box-inner-text sofiabold h2 velure'><%= Rails.application.secrets.name %> is about getting involved in your community one day, and one cause at a time.</p>
      </div>
      <div class='faq-container'>
        <div class='faq-text-box'>
          <p class='faq-subheading sofiabold h4 dgray'>One is greater than one million</p>
          <p class='faq-text h5 lgray pt1'>
            "In the fundraising business, there’s an old axiom that 'one is greater than one million.' This isn’t bad math; it is a reminder that when it comes to people in need, one million is a statistic, while one is a human story.”
            <br/><span class='velure'>- Arthur C. Brooks</span>
          </p>
          <p class='faq-text h5 lgray pt1'>
            Towards the end of last year, a group of friends from different walks of life came together over a shared sense of wanting to give back.
          </p>
          <p class='faq-text h5 lgray pt1'>
            Consistent with Brooks’ idea, we wanted to focus on helping the individuals who make up our own community; however, we found it challenging to identify, connect to, and participate with the organizations around us in a meaningful and reoccurring way.
          </p>
        </div>
        <div class='faq-text-box'>
          <p class='faq-subheading sofiabold h4 dgray'>Team <%= Rails.application.secrets.name %></p>
          <p class='faq-text h5 lgray pt1'>
            Gin Lane, Bond Street Hospitality, The Setting, Lola New York, Samantha Orley, AGW Group, Dmitri Vassilev, Sanctuary Computer & <span class='velure'>You.</span>
          </p>
        </div>
        <div class='faq-text-box'>
          <p class='faq-subheading sofiabold h4 dgray'>How we operate</p>
          <p class='faq-text h5 lgray pt1'>
            <%= Rails.application.secrets.name %> is a non-profit federal tax-exempt organization under section 501(c)(3) of the Internal Revenue Code, EIN 81-4924613, so all of your donations are tax deductible.
          </p>
          <p class='faq-text h5 lgray pt1'>
            The money you donate goes directly to the selected charities. We don’t take a penny.
          </p>
          <p class='faq-text h5 lgray pt1'>
            We’re run by a team of volunteers, and all of our administrative costs are supported by private philanthropy which enables us to ensure every dollar raised goes directly to supporting the causes you care about most. Interested in supporting the platform? You can reach us at <span class='velure'>hello@give-one.org↳.</span> We’d love to continue the conversation!
          </p>
        </div>
      </div>
    </div>
  </div>

</div>

app/views/site/legal.html.erb
<article id="content" class="bg-white js-donate-button-hide">
  <section id="intro" class="hero-legal intro bg-grey pt8 pb8">
    <div class="container p2">
      <div class="col-center col-8">
        <h2 class="white no-margin"><%= Rails.application.secrets.name %> is a simple service that we’ve endeavored to make easy to understand.</h2>
      </div>
    </div>
  </section>

  <section class="bg-green pt4 pb4">
    <div class="container p2">
      <div class="col-center col-8">

        <div class="mb6">
          <h3 class="bold mb2">Our Terms of Service &amp; Privacy Policy</h3>
          <p>ToS goes in here...</p>
        </div>

      </div>
    </div>
  </section>
</article>

app/views/site/share.html.erb
<!DOCTYPE html>
<html>
<head>
  <title></title>
</head>
<body>
  <div id="site_share">
    <code id="url" style="display:none;"> <%= @full_url %> </code>
    <!-- <code> <%= @full_url %> </code> -->
  </div>

  <%= javascript_include_tag "share" %>
</body>
</html>

app/views/site/volunteer.html.erb
<div class='clearfix'>

    <div class='col col-12 py4 border-first-panel relative bc-white bg-mandarine min-panel-height' style='z-index:1'>
      <div class='clearfix py4 px2 flex items-center mx-auto'>
        <div class='col col-12 py4 flex flex-column center'>
          <div class='max-width-3 mx-auto'>
            <p class='mx-auto h1 my0 sofiabold pb1 dgray'>Connect to your community through<span class='accent-color'> volunteering.</span></p>
            <p class='mx-auto h5 MuseoSans300 px4 py3 dgray'>
              Volunteer with local, credible community organization (currently beta testing in NYC).
            </p>
          </div>

          <%= render "layouts/public/partials/category_cards", locals: @categories, mode: "filter" %>

          <div id='collapse-sub-header'></div>
          <% content_for :sub_header do %>
            <%= render "layouts/public/partials/activations_sub_header", locals: @categories %>
          <% end %>

        </div>
      </div>
    </div>

    <div class='before-faq-panel col col-12 py4 my4 bg-mandarine min-panel-height'>
      <div class='clearfix flex items-center flex-wrap justify-center'>
        <% @activations.each do |activation| %>
          <%= render "layouts/public/partials/activation_card", activation: activation %>
        <% end %>
      </div>
    </div>

    <div class='faq-panel col col-12 pb4 min-panel-height'>
      <div class='clearfix pb4 px2 mx-auto max-width-4'>
        <div class='double-border-box-faq biggest-box index-page-box p1'>
          <p class='box-inner-text sofiabold h4 dgray'>A platform for activism</p>
          <p class='box-inner-text sofiabold h2 accent-color'><%= Rails.application.secrets.name %> is about getting involved in your community one day, and one cause at a time.</p>
        </div>
        <div class='faq-container'>
          <div class='faq-text-box'>
            <p class='sub-heading sofiabold dgray'>The fine print</p>
            <p class='faq-subheading sofiabold dgray h4'>How we operate</p>
            <p class='faq-text h5'>
              <%= Rails.application.secrets.name %> is a non-profit federal tax-exempt organization under section 501(c)(3) of the Internal Revenue Code, EIN 81-4924613, so all of your donations are tax deductible.
            </p>
            <p class='faq-text h5'>
              While volunteering doesn’t cost any money, some activations might require tools and supplies, most of which <%= Rails.application.secrets.name %> aims to provide. Interested in donating supplies? Email us at <a class="accent-color text-decoration-none" href="mailto:hello@<%= Rails.application.secrets.host %>">hello@<%= Rails.application.secrets.host %>↳</a>.
            </p>
            <p class='faq-text h5'>
              We’re run by a team of volunteers, and all of our administrative costs are supported by private philanthropy which enables us to ensure every dollar raised goes directly to supporting the causes you care about most. Interested in supporting the platform? You can reach us at <a class="accent-color text-decoration-none" href="mailto:hello@<%= Rails.application.secrets.host %>">hello@<%= Rails.application.secrets.host %>↳</a>. We’d love to continue the conversation!
            </p>
          </div>
          <div class='faq-text-box'>
            <p class='faq-subheading sofiabold dgray h4'>Liability & responsibility</p>
            <p class='faq-text h5'>
              Our goal is to connect willing and able volunteers directly with credible community organizations.
            </p>
            <p class='faq-text h5'>
              <%= Rails.application.secrets.name %> is not liable for any personal damages, injury, or lost property during participant’s activation. Before an activation, each volunteer is required to fill out a waiver.
            </p>
            <p class='faq-text h5'>
              While we help coordinate the activations, you’ll be dealing directly with the organizations who may have their own requirements and paperwork for you to fill out.
            </p>
            <p class='faq-text h5'>
              If you have any specific questions, email us at <a class="accent-color text-decoration-none" href="mailto:hello@give-one.org">hello@give-one.org↳</a>.
            </p>
          </div>
          <div class='faq-text-box'>
            <p class='faq-subheading sofiabold dgray h4'>We're in beta</p>
            <p class='faq-text h5'>
              We are currently Beta testing our volunteer activations with select partners in New York City.
            </p>
            <p class='faq-text h5'>
              We will be expanding our programming to additional communities and community organizers in the months to come. If you have an organization that would like to participate, or would like to suggest an organization, please email us at <a class="accent-color text-decoration-none" href="mailto:partners@give-one.org">partners@give-one.org↳</a>.
            </p>
            <p class='faq-text accent-color h5'>
              We’d love to help!
            </p>
          </div>
        </div>
      </div>
    </div>
</div>

app/views/site/wall_calendar.html.erb
<%
calendar_dates = [2.months.ago.to_date, 1.month.ago.to_date, Time.zone.now.to_date]
(1..2).each do |i|
  calendar_dates << i.months.from_now.to_date
end
%>

<section id="nonprofits" class="pt6 pb6 pl4 pr4 bg-green z-index-1">
  <div id="carousel" class="content">
    <div class="header mb4 col-6 left">
      <h2 class="normal-weight">Our nonprofit calendar</h2>
    </div>
    <nav id="calendar_nav" class="right">
      <div class="select-box">
        <div class="title">
          <span class="mr2">February</span>
          <span class="ss-icon ss-dropdown"></span>
        </div>
        <div class="dropdown hide">
          <ul>
            <% calendar_dates.each do |calendar_date| %>
              <li class="grey small_type <%= 'selected' if calendar_date.month == Time.zone.now.to_date.month %>">
                <%= calendar_date.strftime("%B") %>
              </li>
            <% end -%>
          </ul>
        </div>
      </div>
    </nav>

    <div id="calendar_carousel" class="cycle-slideshow clear" data-cycle-fx="scrollHorz" data-cycle-timeout="0" data-cycle-slides="> div" data-cycle-pager="#calendar_nav ul" data-cycle-pager-template="" data-cycle-log="false">
      <% calendar_dates.each do |calendar_date| %>
        <div class="slide"><%= render 'nonprofits/calendar', date: calendar_date %></div>
      <% end -%>
    </div>
  </div>
</section>