config/routes.rb
Rails.application.routes.draw do
  root to: 'site#index'

  resources :donors do
    member do
      put 'cancel'
      put 'uncancel'
    end
    collection do
      get 'exists'
      put 'verify'
      get 'thanks'
      get 'fetch_state_by_zip'
      get 'map'
      post 'payment_receipt'
    end
  end

  resources :nonprofits do
    get 'autotweet', on: :member
    get 'upcoming_report', on: :collection
  end

  resources :subscribers, param: :guid do
    member do
      get 'unsubscribe',                action: 'unsubscribe',  as: 'unsubscribe'
      put 'unsubscribe'
      put 'resubscribe'
      get 'donations',                  action: 'donations'
      get 'email_login/:auth_token',    action: 'email_login',  as: 'email_login'
      get 'logout',                     action: 'logout'
    end
    collection do
      get 'thanks'
    end
  end

  devise_for :users, :skip => [:registrations]
  devise_scope :user do
    get "login"      => "devise/sessions#new"
    get 'users/edit' => 'devise/registrations#edit',   as: 'edit_user_registration'
    put 'users'      => 'devise/registrations#update', as: 'user_registration'
  end

  resources :users

  # These were added by hugh
  get  'volunteer',        to: 'site#volunteer'
  get  'account',          to: 'site#account',       as: :account
  get  'donate',           to: 'donors#info',        as: :donate
  get  'donate/:id',       to: 'donors#new',         as: :new_donation

  #TODO: Scrub below routes
  get  'about',            to: 'site#about'
  get  'calendar',         to: 'site#calendar'
  get  'faq',              to: 'site#faq'
  get  'subscribe',        to: 'subscribers#new',    as: :subscribe
  post 'donate',           to: 'donors#create'
  get  'legal',            to: 'site#legal'
  get  'contact',          to: 'site#contact'
  post 'send_feedback',    to: 'site#send_feedback'
  get  'wall_calendar',    to: 'site#wall_calendar'
  get  'autotweet',        to: 'site#autotweet'
  # Share to app (or) mobile browser javascript
  get 'share',             to: 'site#share',         as: :share

  # Admin
  get '/admin/mailers'         => "admin/mailers#index"
  get '/admin/mailers/*path'   => "admin/mailers#preview"

  namespace :admin do
    get 'delayed_jobs', to: 'base#delayed_jobs'

    resources :categories
    resources :nonprofits do
      collection do
        get :lookup_ein
      end
    end
    resources :activations
    resources :donors, except: [:new, :create]
    resources :donations
    resources :subscribers
    resources :stats
    resources :payouts, only: [:index, :create]
  end

  get '/health' => 'application#health'
end

app/views/layouts/partials/_admin_bar.html.erb
<% link_class = "MuseoSans300 text-decoration-none accent-color pr1" %>
<div class='admin-header p2 flex justify-between dgray sofiabold'>
  <div class='nav-links flex max-width-none'>
    <div class="links tablet-center row">
      <div class="tablet-col-right" style="color: black;">
        <%= link_to_unless_current "Categories", admin_categories_url, class: link_class %>
        &nbsp;&nbsp;&nbsp;
        <%= link_to_unless_current "Nonprofits", admin_nonprofits_url, class: link_class %>
        &nbsp;&nbsp;&nbsp;
        <%= link_to_unless_current "Activations", admin_activations_url, class: link_class %>
        &nbsp;&nbsp;&nbsp;
        <%= link_to_unless_current "Stats", admin_stats_url, class: link_class %>
        &nbsp;&nbsp;&nbsp;
        <!-- <%= link_to_unless_current "Emails", "/admin/mailers", class: link_class  %>
        &nbsp;&nbsp;&nbsp; -->
        <%= link_to_unless_current "Subscribers", admin_subscribers_url, class: link_class  %>
        &nbsp;&nbsp;&nbsp;
        <%= link_to_unless_current "Donors", admin_donors_url, class: link_class  %>
        &nbsp;&nbsp;&nbsp;
        <!-- <%= link_to_unless_current "Payouts", admin_payouts_url, class: link_class  %>
        &nbsp;&nbsp;&nbsp; -->
        <%= link_to_unless_current "Delayed Jobs", admin_delayed_jobs_url, class: link_class  %>
        &nbsp;&nbsp;&nbsp;
        <%= link_to "Logout", destroy_user_session_url, method: :delete, class: link_class  %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/partials/_cta_know_more.html.erb
<aside class="bg-pattern white"><div class="px-gutter py6 centered col-max-10 col-center">
  <div class="big">
    <p class="mb0 bold"><%= Rails.application.secrets.name %> is a simple new way to discover and support amazing nonprofits.</p>
    <p class="mb3">We feature one great organization every day, everyone automatically donates&nbsp;$1.</p>
  </div>
  <p class="mb0"><%= link_to "Learn More", root_path, class: "button-outline button-white button-hover-black" %></p>
</div></aside>

app/views/layouts/partials/_footer.html.erb
<footer class="main bg-green clip"><div class="container p2">
  <div class="links tablet-center row">
    <div class="tablet-col grey"><span class="small mobile-block py1">&copy; <%= Time.zone.now.year %> <%= Rails.application.secrets.name %></span></div>
    <div class="tablet-col-right">
      <span class="mobile-block py1">
        <%= link_to "Home", root_path(ref: "footer"), class: "small inline-block pr1 pl1 pb1 grey #{'hide' if controller.controller_name == 'site' and controller.action_name == 'index'}" %>
        <%= link_to "FAQ", faq_path(ref: "footer"), class: "small inline-block pr1 pl1 pb1 grey" %>
        <%= link_to "Contact", contact_path(ref: "footer"), class: "small inline-block pr1 pl1 pb1 grey" %>
        <%= link_to "Terms & Privacy", legal_path(ref: "footer"), class: "small inline-block pr1 pl1 pb1 grey" %>
        <%- if current_subscriber? -%>
        <%= link_to "Account", subscriber_path(current_subscriber), class: "small inline-block pr1 pl1 pb1 grey" %>
        <%- else -%>
        <%= link_to "Manage account", "#authenticate-overlay", id: "authenticate_link", class: "small js-modal-overlay-open no-wrap inline-block pr2 pl1 pb1 grey" %>
        <%- end -%>
      </span>
      <span class="mobile-show big py1">
        <a href="https://twitter.com/<%= Rails.application.secrets.twitter_username %>" target="_blank" class="inline-block grey no-decoration color-twitter-hover"><span class="ss-icon ss-social-circle ss-twitter transition-all"></span></a>
        <a href="https://www.facebook.com/<%= Rails.application.secrets.facebook_username %>" target="_blank" class="inline-block grey no-decoration color-facebook-hover"><span class="ss-icon ss-social-circle ss-facebook transition-all"></span></a>
      </span>
      <span class="mobile-hide py1">
        <a href="https://twitter.com/<%= Rails.application.secrets.twitter_username %>" target="_blank" class="inline-block grey no-decoration color-twitter-hover"><span class="ss-icon ss-social-circle ss-twitter transition-all"></span></a>
        <a href="https://www.facebook.com/<%= Rails.application.secrets.facebook_username %>" target="_blank" class="inline-block grey no-decoration color-facebook-hover"><span class="ss-icon ss-social-circle ss-facebook transition-all"></span></a>
      </span>
    </div>
  </div>
</div></footer>
<% if current_user.try(:is_admin?) %>
  <div class="footer_prop"></div>
<% end %>
<%= render 'donors/authenticate_form' %>

app/views/layouts/partials/_head.html.erb
<script src="//cdn.optimizely.com/js/2495470497.js"></script>
<title>
  <%= (@page_title ? "#{@page_title} — #{Rails.application.secrets.name}": Rails.application.secrets.name) %>
</title>
<link href="/favicon.png" type="image/png" rel="icon" />
<meta name="viewport" content="width=device-width,initial-scale=1">
<meta content="text/html; charset=utf-8" http-equiv="Content-Type">
<%= meta_tags %>
<%= csrf_meta_tags %>
<%= stylesheet_link_tag    "application", media: "all" %>
<%= javascript_include_tag "application", async: !true %>
<%= javascript_include_tag "admin", async: !true if current_user.try(:is_admin?) %>
<% if @require_stripe_js %>
<script type="text/javascript" src="https://js.stripe.com/v2/"></script>
<script type="text/javascript">
  // This identifies your website in the createToken call below
  Stripe.setPublishableKey("<%= Rails.application.secrets.stripe_publishable_key %>");
</script>
<% end %>

app/views/layouts/partials/_header.html.erb
<div class='header my2 flex justify-between dgray sofiabold'>
  <a class='text-decoration-none dgray flex items-center mx1' href="/">
    <p class='logo h4 nowrap'><%= Rails.application.secrets.name %></p>
  </a>
  <div class='nav-links flex max-width-2'>
    <a class='text-decoration-none dgray flex items-center mx2' href="/donate">
      <div class='icons px2' id='money'></div>
      <p class='h6 donate'>Donate</p>
    </a>
    <a class='text-decoration-none dgray flex items-center mx2' href="/volunteer">
      <div class='icons px2' id='activation'></div>
      <p class='h6 activation'>Volunteer</p>
    </a>
    <a class='text-decoration-none dgray flex items-center mx2' href="/account">
      <div class='icons px2' id='account'></div>
      <p class='h6 account'>Account</p>
    </a>
  </div>
</div>

app/views/layouts/partials/_scripts.html.erb
<% if Rails.application.secrets.google_analytics_id %>
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.asynck=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
  ga('create', '<%= Rails.application.secrets.google_analytics_id %>', 'auto');
  ga('send', 'pageview');
</script>
<% end %>

<%# Don't include tracking scripts on new donor page %>
<% if page_id != "donors_new" && page_id != "donors_create" %>

  <!-- Facebook -->
  <div id="fb-root"></div>
  <script>
    window.fbAsyncInit = function() {
      FB.init({
        appId      : '<%= Rails.application.secrets.facebook_app_id %>',
        xfbml      : true,
        version    : 'v2.3'
      });
    };
    (function(d, s, id){
       var js, fjs = d.getElementsByTagName(s)[0];
       if (d.getElementById(id)) {return;}
       js = d.createElement(s); js.id = id;
       js.src = "//connect.facebook.net/en_US/sdk.js";
       fjs.parentNode.insertBefore(js, fjs);
     }(document, 'script', 'facebook-jssdk'));
  </script>

  <!-- Twitter -->
  <script>
  window.twttr=(function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],t=window.twttr||{};if(d.getElementById(id))return t;js=d.createElement(s);js.id=id;js.src="https://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);t._e=[];t.ready=function(f){t._e.push(f);};return t;}(document,"script","twitter-wjs"));
  </script>

<% end %>